#!/usr/bin/env python3
"""
download_and_serve_cms_editor.py

Purpose:
  Download the existing R2 CMS editor HTML into this repo and patch worker.js so
  https://agent.meauxbility.workers.dev/cms serves that downloaded CMS editor.

Source:
  https://pub-3656a00174f24106b656b8dcf3ba783c.r2.dev/cms-editor-index.html

What it changes:
  - downloads to public/cms/cms-editor-index.html
  - creates/updates src/generated/cms-editor-html.js
  - patches worker.js with:
      import { CMS_EDITOR_HTML } from './src/generated/cms-editor-html.js';
      if pathname === '/cms' or '/cms/' return CMS_EDITOR_HTML
  - writes scripts/cms/smoke_cms_route.sh

No DB mutation.
No R2 write.
No model calls.
"""

from __future__ import annotations

import json
import re
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
WORKER = ROOT / "worker.js"
PUBLIC_CMS_DIR = ROOT / "public" / "cms"
CMS_HTML = PUBLIC_CMS_DIR / "cms-editor-index.html"
GENERATED_DIR = ROOT / "src" / "generated"
GENERATED_JS = GENERATED_DIR / "cms-editor-html.js"
SMOKE = ROOT / "scripts" / "cms" / "smoke_cms_route.sh"

SRC_URL = "https://pub-3656a00174f24106b656b8dcf3ba783c.r2.dev/cms-editor-index.html"

IMPORT_LINE = "import { CMS_EDITOR_HTML } from './src/generated/cms-editor-html.js';"
START = "// AGENT_MEAUXBILITY_CMS_ROUTE_START"
END = "// AGENT_MEAUXBILITY_CMS_ROUTE_END"

ROUTE_BLOCK = f"""
{START}
  if (url.pathname === '/cms' || url.pathname === '/cms/') {{
    return new Response(CMS_EDITOR_HTML, {{
      status: 200,
      headers: {{
        'content-type': 'text/html;charset=UTF-8',
        'cache-control': 'no-store'
      }}
    }});
  }}
{END}
""".rstrip()


def stamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")


def run(cmd: list[str]) -> str:
    proc = subprocess.run(cmd, cwd=ROOT, text=True, capture_output=True)
    if proc.returncode != 0:
        raise SystemExit(
            "Command failed: " + " ".join(cmd) + "\n"
            + "STDOUT:\n" + proc.stdout + "\n"
            + "STDERR:\n" + proc.stderr
        )
    return proc.stdout


def backup(path: Path) -> None:
    if path.exists():
        dst = path.with_suffix(path.suffix + ".backup." + stamp())
        shutil.copy2(path, dst)
        print(f"backup -> {dst}")


def download_html() -> None:
    PUBLIC_CMS_DIR.mkdir(parents=True, exist_ok=True)
    run(["/usr/bin/curl", "-L", "--fail", "--silent", "--show-error", SRC_URL, "-o", str(CMS_HTML)])
    size = CMS_HTML.stat().st_size
    if size < 1000:
        raise SystemExit(f"Downloaded CMS HTML is suspiciously small: {size} bytes")
    text = CMS_HTML.read_text(errors="replace")
    if "<html" not in text.lower() and "<!doctype" not in text.lower():
        raise SystemExit("Downloaded file does not look like HTML")
    print(f"downloaded -> {CMS_HTML} ({size} bytes)")


def write_generated_module() -> None:
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    html = CMS_HTML.read_text(errors="replace")
    GENERATED_JS.write_text(
        "// Generated by scripts/cms/download_and_serve_cms_editor.py\n"
        "// Source: " + SRC_URL + "\n"
        "// Do not hand-edit this file; edit public/cms/cms-editor-index.html and regenerate.\n\n"
        "export const CMS_EDITOR_HTML = " + json.dumps(html) + ";\n"
    )
    print(f"generated -> {GENERATED_JS}")


def insert_import(worker: str) -> str:
    if IMPORT_LINE in worker:
        return worker

    # Put import before first existing import, otherwise at top.
    if worker.lstrip().startswith("import "):
        return IMPORT_LINE + "\n" + worker

    return IMPORT_LINE + "\n" + worker


def replace_existing_block(worker: str) -> str | None:
    if START in worker and END in worker:
        return re.sub(
            re.escape(START) + r".*?" + re.escape(END),
            ROUTE_BLOCK,
            worker,
            flags=re.S,
        )
    return None


def insert_route_block(worker: str) -> str:
    replaced = replace_existing_block(worker)
    if replaced is not None:
        return replaced

    # Best case: insert immediately after URL creation.
    patterns = [
        r"(const\s+url\s*=\s*new\s+URL\s*\(\s*request\.url\s*\)\s*;)",
        r"(let\s+url\s*=\s*new\s+URL\s*\(\s*request\.url\s*\)\s*;)",
        r"(var\s+url\s*=\s*new\s+URL\s*\(\s*request\.url\s*\)\s*;)",
    ]

    for pattern in patterns:
        m = re.search(pattern, worker)
        if m:
            return worker[:m.end()] + "\n" + ROUTE_BLOCK + worker[m.end():]

    # Fallback: find a fetch(request, env...) opening brace.
    m = re.search(r"(async\s+fetch\s*\([^)]*\)\s*\{)", worker)
    if m:
        return worker[:m.end()] + "\n  const url = new URL(request.url);\n" + ROUTE_BLOCK + worker[m.end():]

    m = re.search(r"(fetch\s*\([^)]*\)\s*\{)", worker)
    if m:
        return worker[:m.end()] + "\n  const url = new URL(request.url);\n" + ROUTE_BLOCK + worker[m.end():]

    raise SystemExit(
        "Could not find a safe insertion point in worker.js. "
        "Search for `new URL(request.url)` or `async fetch` and patch manually."
    )


def patch_worker() -> None:
    if not WORKER.exists():
        raise SystemExit("worker.js not found")

    backup(WORKER)
    worker = WORKER.read_text(errors="replace")
    worker = insert_import(worker)
    worker = insert_route_block(worker)
    WORKER.write_text(worker)
    print("patched -> worker.js")


def write_smoke() -> None:
    SMOKE.parent.mkdir(parents=True, exist_ok=True)
    SMOKE.write_text(
        "#!/usr/bin/env bash\n"
        "set -euo pipefail\n"
        'BASE="${AGENT_MEAUXBILITY_APP_URL:-https://agent.meauxbility.workers.dev}"\n'
        'echo "== /cms headers =="\n'
        '/usr/bin/curl -I "${BASE}/cms" | /usr/bin/sed -n "1,14p"\n'
        'echo ""\n'
        'echo "== /cms body markers =="\n'
        '/usr/bin/curl -sS "${BASE}/cms" | /usr/bin/grep -Ei "cms-editor|Start Building Your Page|Section Library|Page Settings|AGENT_MEAUXBILITY_MPA_ROUTE_BRIDGE" | /usr/bin/head -20 || true\n'
    )
    SMOKE.chmod(0o755)
    print(f"wrote -> {SMOKE}")


def main() -> int:
    download_html()
    write_generated_module()
    patch_worker()
    write_smoke()

    print()
    print("Next:")
    print("  python3 -m py_compile scripts/cms/download_and_serve_cms_editor.py")
    print("  npx wrangler deploy --dry-run -c wrangler.json")
    print("  npx wrangler deploy -c wrangler.json")
    print("  scripts/cms/smoke_cms_route.sh")
    print("  open https://agent.meauxbility.workers.dev/cms")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
