#!/usr/bin/env python3
from __future__ import annotations

import json
import re
import shutil
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

INDEX_HTML = ROOT / "index.html"
CMS_HTML = ROOT / "public" / "cms" / "cms-editor-index.html"
CMS_GENERATED_JS = ROOT / "src" / "generated" / "cms-editor-html.js"

COMPONENT_DIR = ROOT / "public" / "components"
HEADER_CSS = COMPONENT_DIR / "agent-global-header.css"
HEADER_JS = COMPONENT_DIR / "agent-global-header.js"

LOGO_URL = "https://imagedelivery.net/g7wf09fCONpnidkRnR_5vw/ac515729-af6b-4ea5-8b10-e581a4d02100/thumbnail"

HEADER_CSS_TEXT = """
/*
  Agent Meauxbility Global Header
  Generated by scripts/cms/part2_global_header_nav.py
*/

:root {
  --am-header-height: 64px;
  --am-header-bg: rgba(7, 8, 10, 0.78);
  --am-header-border: rgba(255, 255, 255, 0.10);
  --am-header-text: rgba(255, 255, 255, 0.94);
  --am-header-muted: rgba(255, 255, 255, 0.58);
  --am-header-soft-hover: rgba(255, 255, 255, 0.13);
  --am-header-accent: #67e8f9;
  --am-header-purple: #7c3aed;
  --am-header-shadow: 0 18px 60px rgba(0, 0, 0, 0.28);
}

html {
  scroll-padding-top: var(--am-header-height);
}

body.has-agent-global-header {
  padding-top: var(--am-header-height);
}

.agent-global-header {
  position: fixed;
  inset: 0 0 auto 0;
  height: var(--am-header-height);
  z-index: 9999;
  display: flex;
  align-items: center;
  justify-content: center;
  border-bottom: 1px solid var(--am-header-border);
  background:
    radial-gradient(circle at 12% 0%, rgba(103, 232, 249, 0.12), transparent 32%),
    radial-gradient(circle at 88% 0%, rgba(124, 58, 237, 0.16), transparent 30%),
    var(--am-header-bg);
  backdrop-filter: blur(18px) saturate(1.35);
  -webkit-backdrop-filter: blur(18px) saturate(1.35);
  box-shadow: var(--am-header-shadow);
  color: var(--am-header-text);
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}

.agent-global-header__inner {
  width: min(100%, 1440px);
  height: 100%;
  display: grid;
  grid-template-columns: minmax(220px, 1fr) auto minmax(220px, 1fr);
  align-items: center;
  gap: 18px;
  padding: 0 22px;
}

.agent-global-header__brand {
  display: inline-flex;
  align-items: center;
  gap: 11px;
  min-width: 0;
  color: inherit;
  text-decoration: none;
}

.agent-global-header__logo-wrap {
  width: 36px;
  height: 36px;
  border-radius: 12px;
  display: grid;
  place-items: center;
  background: rgba(255, 255, 255, 0.06);
  border: 1px solid rgba(255, 255, 255, 0.11);
  overflow: hidden;
}

.agent-global-header__logo {
  width: 28px;
  height: 28px;
  object-fit: contain;
  display: block;
}

.agent-global-header__wordmark {
  min-width: 0;
  display: flex;
  flex-direction: column;
  line-height: 1.05;
}

.agent-global-header__title {
  font-size: 13px;
  font-weight: 700;
  letter-spacing: -0.01em;
  white-space: nowrap;
}

.agent-global-header__subtitle {
  margin-top: 3px;
  color: var(--am-header-muted);
  font-size: 11px;
  white-space: nowrap;
}

.agent-global-header__nav {
  height: 42px;
  padding: 4px;
  display: inline-flex;
  align-items: center;
  gap: 4px;
  border-radius: 999px;
  background: rgba(255, 255, 255, 0.055);
  border: 1px solid rgba(255, 255, 255, 0.10);
}

.agent-global-header__link {
  position: relative;
  height: 32px;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  padding: 0 13px;
  border-radius: 999px;
  color: var(--am-header-muted);
  text-decoration: none;
  font-size: 12px;
  font-weight: 650;
  letter-spacing: -0.01em;
  transition: color 160ms ease, background 160ms ease, transform 160ms ease;
}

.agent-global-header__link:hover {
  color: var(--am-header-text);
  background: var(--am-header-soft-hover);
}

.agent-global-header__link[data-active="true"] {
  color: #061014;
  background: linear-gradient(135deg, rgba(103, 232, 249, 0.96), rgba(167, 139, 250, 0.96));
  box-shadow: 0 10px 28px rgba(103, 232, 249, 0.12);
}

.agent-global-header__actions {
  justify-self: end;
  display: inline-flex;
  align-items: center;
  gap: 8px;
}

.agent-global-header__pill {
  height: 32px;
  display: inline-flex;
  align-items: center;
  gap: 7px;
  padding: 0 11px;
  border-radius: 999px;
  background: rgba(255, 255, 255, 0.055);
  border: 1px solid rgba(255, 255, 255, 0.10);
  color: var(--am-header-muted);
  font-size: 11px;
  font-weight: 650;
  white-space: nowrap;
}

.agent-global-header__dot {
  width: 7px;
  height: 7px;
  border-radius: 999px;
  background: #34d399;
  box-shadow: 0 0 0 4px rgba(52, 211, 153, 0.13);
}

.agent-global-header__button {
  height: 32px;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  padding: 0 12px;
  border-radius: 999px;
  color: var(--am-header-text);
  text-decoration: none;
  font-size: 11px;
  font-weight: 750;
  border: 1px solid rgba(255, 255, 255, 0.12);
  background: linear-gradient(135deg, rgba(124, 58, 237, 0.86), rgba(14, 165, 233, 0.72));
}

.agent-global-header__menu {
  display: none;
  width: 36px;
  height: 36px;
  border: 0;
  border-radius: 12px;
  color: var(--am-header-text);
  background: rgba(255, 255, 255, 0.07);
}

.agent-global-header__menu span,
.agent-global-header__menu::before,
.agent-global-header__menu::after {
  content: "";
  display: block;
  width: 16px;
  height: 2px;
  margin: 4px auto;
  border-radius: 99px;
  background: currentColor;
}

.agent-global-header__mobile-panel {
  display: none;
}

@media (max-width: 860px) {
  .agent-global-header__inner {
    grid-template-columns: 1fr auto;
    padding: 0 14px;
  }

  .agent-global-header__nav,
  .agent-global-header__actions {
    display: none;
  }

  .agent-global-header__menu {
    display: block;
  }

  .agent-global-header[data-open="true"] .agent-global-header__mobile-panel {
    position: fixed;
    top: calc(var(--am-header-height) + 8px);
    left: 12px;
    right: 12px;
    display: grid;
    gap: 8px;
    padding: 12px;
    border-radius: 18px;
    background: rgba(10, 11, 14, 0.94);
    border: 1px solid rgba(255, 255, 255, 0.12);
    box-shadow: 0 24px 80px rgba(0, 0, 0, 0.42);
  }

  .agent-global-header__mobile-panel a {
    color: var(--am-header-text);
    text-decoration: none;
    padding: 12px 13px;
    border-radius: 12px;
    background: rgba(255, 255, 255, 0.055);
    font-size: 13px;
    font-weight: 700;
  }

  .agent-global-header__subtitle {
    display: none;
  }
}
""".strip() + "\n"

HEADER_JS_TEXT = """
/*
  Agent Meauxbility Global Header
  Generated by scripts/cms/part2_global_header_nav.py
*/
(function AgentMeauxbilityGlobalHeader() {
  "use strict";

  var LOGO_URL = "__LOGO_URL__";
  var ROUTES = [
    { path: "/", label: "Agents" },
    { path: "/automations", label: "Automations" },
    { path: "/dashboard", label: "Dashboard" },
    { path: "/cms", label: "CMS Editor" }
  ];

  function normalize(pathname) {
    var path = pathname || "/";
    path = path.replace(/\\/+$/, "");
    return path || "/";
  }

  function isActive(path) {
    var current = normalize(window.location.pathname);
    return current === normalize(path);
  }

  function navLinks(className) {
    return ROUTES.map(function(route) {
      return [
        "<a class='" + className + "'",
        " href='" + route.path + "'",
        " data-agent-global-route='" + route.path + "'",
        " data-active='" + (isActive(route.path) ? "true" : "false") + "'",
        ">" + route.label + "</a>"
      ].join("");
    }).join("");
  }

  function hideLegacyHeader() {
    var route = normalize(window.location.pathname);

    if (route === "/cms") {
      return;
    }

    var candidates = Array.prototype.slice.call(document.querySelectorAll("header, nav"));
    candidates.forEach(function(el) {
      var text = (el.textContent || "").replace(/\\s+/g, " ").trim();
      if (
        text.indexOf("Agents") !== -1 &&
        text.indexOf("Automations") !== -1 &&
        text.indexOf("Dashboard") !== -1
      ) {
        el.setAttribute("data-agent-legacy-nav-hidden", "true");
        el.style.display = "none";
      }
    });
  }

  function buildHeader() {
    if (document.querySelector(".agent-global-header")) return;

    var header = document.createElement("header");
    header.className = "agent-global-header";
    header.setAttribute("data-open", "false");

    header.innerHTML = [
      "<div class='agent-global-header__inner'>",
      "  <a class='agent-global-header__brand' href='/' aria-label='Agent Meauxbility home'>",
      "    <span class='agent-global-header__logo-wrap'>",
      "      <img class='agent-global-header__logo' src='" + LOGO_URL + "' alt='Meauxbility logo' loading='eager' decoding='async'>",
      "    </span>",
      "    <span class='agent-global-header__wordmark'>",
      "      <span class='agent-global-header__title'>Agent Meauxbility</span>",
      "      <span class='agent-global-header__subtitle'>CMS + agent platform</span>",
      "    </span>",
      "  </a>",
      "  <nav class='agent-global-header__nav' aria-label='Primary navigation'>",
      navLinks("agent-global-header__link"),
      "  </nav>",
      "  <div class='agent-global-header__actions'>",
      "    <span class='agent-global-header__pill'><span class='agent-global-header__dot'></span>Live</span>",
      "    <a class='agent-global-header__button' href='/cms'>Open CMS</a>",
      "  </div>",
      "  <button class='agent-global-header__menu' type='button' aria-label='Toggle navigation'><span></span></button>",
      "</div>",
      "<div class='agent-global-header__mobile-panel'>",
      navLinks("agent-global-header__mobile-link"),
      "</div>"
    ].join("");

    document.body.insertBefore(header, document.body.firstChild);
    document.body.classList.add("has-agent-global-header");

    var menu = header.querySelector(".agent-global-header__menu");
    if (menu) {
      menu.addEventListener("click", function() {
        header.setAttribute("data-open", header.getAttribute("data-open") === "true" ? "false" : "true");
      });
    }
  }

  function boot() {
    buildHeader();
    hideLegacyHeader();
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", boot);
  } else {
    boot();
  }
})();
""".replace("__LOGO_URL__", LOGO_URL).strip() + "\n"


def stamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")


def backup(path: Path) -> None:
    if path.exists():
        dst = path.with_suffix(path.suffix + ".backup." + stamp())
        shutil.copy2(path, dst)
        print("backup ->", dst)


def ensure_head_assets(html: str, css_href: str, js_src: str) -> str:
    css_tag = f'<link rel="stylesheet" href="{css_href}" data-agent-global-header="css">'
    js_tag = f'<script src="{js_src}" defer data-agent-global-header="js"></script>'

    html = re.sub(r'\s*<link[^>]+data-agent-global-header="css"[^>]*>', "", html)
    html = re.sub(r'\s*<script[^>]+data-agent-global-header="js"[^>]*></script>', "", html)

    match = re.search(r"</head\s*>", html, flags=re.I)
    if match:
        return html[:match.start()] + "\n  " + css_tag + "\n  " + js_tag + "\n" + html[match.start():]

    return css_tag + "\n" + js_tag + "\n" + html


def patch_html_file(path: Path, css_href: str, js_src: str) -> None:
    if not path.exists():
        raise SystemExit(f"Missing HTML file: {path}")

    backup(path)
    html = path.read_text(errors="replace")
    path.write_text(ensure_head_assets(html, css_href, js_src))
    print("patched ->", path)


def write_components() -> None:
    COMPONENT_DIR.mkdir(parents=True, exist_ok=True)
    HEADER_CSS.write_text(HEADER_CSS_TEXT)
    HEADER_JS.write_text(HEADER_JS_TEXT)
    print("wrote ->", HEADER_CSS)
    print("wrote ->", HEADER_JS)


def regenerate_cms_module() -> None:
    if not CMS_HTML.exists():
        print("skip generated cms module; missing", CMS_HTML)
        return

    CMS_GENERATED_JS.parent.mkdir(parents=True, exist_ok=True)
    html = CMS_HTML.read_text(errors="replace")
    CMS_GENERATED_JS.write_text(
        "// Generated by scripts/cms/part2_global_header_nav.py\n"
        "// Source: public/cms/cms-editor-index.html\n\n"
        "export const CMS_EDITOR_HTML = " + json.dumps(html) + ";\n"
    )
    print("regenerated ->", CMS_GENERATED_JS)


def main() -> int:
    write_components()

    patch_html_file(
        INDEX_HTML,
        "/components/agent-global-header.css",
        "/components/agent-global-header.js",
    )

    if CMS_HTML.exists():
        patch_html_file(
            CMS_HTML,
            "/components/agent-global-header.css",
            "/components/agent-global-header.js",
        )
        regenerate_cms_module()
    else:
        print("cms editor html missing; skipped CMS HTML patch:", CMS_HTML)

    print()
    print("Next:")
    print("  npx wrangler deploy --dry-run -c wrangler.json")
    print("  npx wrangler deploy -c wrangler.json")
    print("  open https://agent.meauxbility.workers.dev/")
    print("  open https://agent.meauxbility.workers.dev/cms")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
