#!/usr/bin/env python3
"""
part5_moon_glass_cms_full_install.py

One-file install for the new Moon Glass CMS baseline.

What this does:
  1. Creates reusable Moon Glass theme artifacts:
       public/themes/moon-glass/theme.css
       public/themes/moon-glass/theme.json

  2. Creates a new Shopify-quality CMS editor shell:
       public/cms/moon-glass-editor.html
       src/generated/moon-glass-cms-editor-html.js

  3. Patches worker.js:
       - imports MOON_GLASS_CMS_EDITOR_HTML
       - serves /cms and /cms/ from the new Moon Glass editor shell
       - installs/updates /api/cms/theme.css runtime endpoint
       - keeps mode=vars and mode=full support

  4. If env is loaded, installs the theme:
       - uploads theme.css to R2 production bucket from CLOUDFLARE_R2_BUCKET
         fallback: inneranimalmedia
       - upserts cms_themes slug=moon-glass into D1 IAM_D1_DB
       - verifies the D1 row

  5. Optionally deploys the Worker:
       default: deploy enabled unless --no-deploy is passed

Required before running:
  source scripts/cms/load-agent-meauxbility-env.sh
  export CLOUDFLARE_API_TOKEN="$AGENT_DASHBOARD_API_TOKEN"

Safe properties:
  - Makes backups before patching worker.js.
  - Does not delete existing CMS snapshot.
  - Does not remove existing themes.
  - Upserts only slug='moon-glass'.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]

WORKER = ROOT / "worker.js"
THEME_DIR = ROOT / "public" / "themes" / "moon-glass"
THEME_CSS = THEME_DIR / "theme.css"
THEME_JSON = THEME_DIR / "theme.json"

CMS_HTML = ROOT / "public" / "cms" / "moon-glass-editor.html"
GENERATED_DIR = ROOT / "src" / "generated"
GENERATED_JS = GENERATED_DIR / "moon-glass-cms-editor-html.js"

SMOKE = ROOT / "scripts" / "cms" / "smoke_moon_glass_cms.sh"

LOGO_URL = "https://imagedelivery.net/g7wf09fCONpnidkRnR_5vw/ac515729-af6b-4ea5-8b10-e581a4d02100/thumbnail"
THEME_SLUG = "moon-glass"
THEME_NAME = "Moon Glass"

THEME_R2_KEY = "cms/themes/moon-glass/theme.css"
THEME_JSON_R2_KEY = "cms/themes/moon-glass/theme.json"
THEME_PUBLIC_URL = "https://assets.inneranimalmedia.com/cms/themes/moon-glass/theme.css"

IMPORT_LINE = "import { MOON_GLASS_CMS_EDITOR_HTML } from './src/generated/moon-glass-cms-editor-html.js';"

CMS_ROUTE_START = "// AGENT_MEAUXBILITY_MOON_GLASS_CMS_ROUTE_START"
CMS_ROUTE_END = "// AGENT_MEAUXBILITY_MOON_GLASS_CMS_ROUTE_END"

THEME_ROUTE_START = "// AGENT_MEAUXBILITY_THEME_CSS_ROUTE_START"
THEME_ROUTE_END = "// AGENT_MEAUXBILITY_THEME_CSS_ROUTE_END"
THEME_HELPER_START = "// AGENT_MEAUXBILITY_THEME_CSS_HELPER_START"
THEME_HELPER_END = "// AGENT_MEAUXBILITY_THEME_CSS_HELPER_END"

MOON_GLASS_TOKENS = {
    "shell_background": "#172333",
    "panel_surface": "#1E2A3A",
    "border_divider": "#2E3B4E",
    "primary_text": "#FAFBFD",
    "secondary_text": "#C7D0DB",
    "muted_text": "#91A0B2",
    "accent_interactive": "#4F8CFF",
    "highlight_glow": "#8FD7FF",
    "pearl_white": "#FAFBFD",
    "mist_gray": "#E9EEF4",
    "moon_gray": "#C7D0DB",
    "blue_gray": "#7A8B9E",
    "deep_navy": "#172333",
    "moon_blue": "#4F8CFF",
    "icy_blue": "#8FD7FF",
    "frost_glow": "#F0FBFF",
    "success": "#34D399",
    "warning": "#F59E0B",
    "danger": "#EF4444",
    "radius_sm": "10px",
    "radius_md": "16px",
    "radius_lg": "22px",
    "radius_xl": "28px",
    "shadow_glass": "0 24px 80px rgba(0,0,0,.34)",
    "font_body": "Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, Segoe UI, sans-serif",
    "font_display": "Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, Segoe UI, sans-serif",
}

MOON_GLASS_CSS = f"""
/*
  Moon Glass theme
  Generated by scripts/cms/part5_moon_glass_cms_full_install.py

  Scope:
    - Reusable CMS/editor theme.
    - Safe to load in full mode on /cms.
    - For the agent app shell, prefer mode=vars only.
*/

:root {{
  --mg-shell-bg: #172333;
  --mg-shell-bg-2: #0E1826;
  --mg-panel: rgba(30, 42, 58, .72);
  --mg-panel-solid: #1E2A3A;
  --mg-panel-soft: rgba(255,255,255,.055);
  --mg-border: rgba(199, 208, 219, .18);
  --mg-border-strong: rgba(143, 215, 255, .28);
  --mg-text: #FAFBFD;
  --mg-text-secondary: #C7D0DB;
  --mg-text-muted: #91A0B2;
  --mg-accent: #4F8CFF;
  --mg-accent-2: #8FD7FF;
  --mg-glow: #F0FBFF;
  --mg-canvas: #F6F9FC;
  --mg-canvas-border: rgba(15, 23, 42, .13);
  --mg-success: #34D399;
  --mg-warning: #F59E0B;
  --mg-danger: #EF4444;
  --mg-radius-sm: 10px;
  --mg-radius-md: 16px;
  --mg-radius-lg: 22px;
  --mg-radius-xl: 28px;
  --mg-shadow: 0 24px 80px rgba(0,0,0,.34);
  --mg-shadow-soft: 0 14px 44px rgba(7, 12, 20, .18);
  --mg-font-body: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  --mg-font-display: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}}

[data-theme="moon-glass"],
.moon-glass-cms {{
  color: var(--mg-text);
  background:
    radial-gradient(circle at 16% -6%, rgba(143,215,255,.18), transparent 28%),
    radial-gradient(circle at 92% 4%, rgba(79,140,255,.15), transparent 30%),
    linear-gradient(135deg, var(--mg-shell-bg-2), var(--mg-shell-bg));
  font-family: var(--mg-font-body);
}}

.moon-glass-card {{
  background: linear-gradient(180deg, rgba(255,255,255,.08), rgba(255,255,255,.045));
  border: 1px solid var(--mg-border);
  box-shadow: var(--mg-shadow-soft);
  border-radius: var(--mg-radius-lg);
  backdrop-filter: blur(18px) saturate(1.2);
  -webkit-backdrop-filter: blur(18px) saturate(1.2);
}}

.moon-glass-pill {{
  border-radius: 999px;
  border: 1px solid var(--mg-border);
  background: rgba(255,255,255,.06);
  color: var(--mg-text-secondary);
}}

.moon-glass-button-primary {{
  border: 1px solid rgba(143,215,255,.32);
  background: linear-gradient(135deg, var(--mg-accent), var(--mg-accent-2));
  color: #06101A;
  font-weight: 800;
  box-shadow: 0 14px 36px rgba(79,140,255,.24);
}}

.moon-glass-button-secondary {{
  border: 1px solid var(--mg-border);
  background: rgba(255,255,255,.055);
  color: var(--mg-text);
}}

.moon-glass-editor-shell {{
  min-height: 100vh;
  display: grid;
  grid-template-rows: 56px 1fr 28px;
  overflow: hidden;
}}

.moon-glass-header {{
  display: grid;
  grid-template-columns: 260px 1fr auto;
  align-items: center;
  gap: 16px;
  padding: 0 16px;
  border-bottom: 1px solid var(--mg-border);
  background: rgba(9, 17, 28, .72);
  backdrop-filter: blur(18px);
}}

.moon-glass-workspace {{
  min-height: 0;
  display: grid;
  grid-template-columns: 54px 260px minmax(520px, 1fr) 300px;
  border-bottom: 1px solid var(--mg-border);
}}

.moon-glass-rail,
.moon-glass-structure,
.moon-glass-inspector {{
  min-height: 0;
  border-right: 1px solid var(--mg-border);
  background: rgba(12, 23, 36, .64);
}}

.moon-glass-inspector {{
  border-right: 0;
  border-left: 1px solid var(--mg-border);
}}

.moon-glass-preview {{
  min-width: 0;
  min-height: 0;
  display: grid;
  place-items: center;
  padding: 20px;
  background:
    radial-gradient(circle at 50% 0%, rgba(143,215,255,.11), transparent 24%),
    rgba(16, 30, 45, .48);
}}

.moon-glass-page-frame {{
  width: min(100%, 980px);
  height: min(100%, 760px);
  border-radius: 14px;
  border: 1px solid rgba(255,255,255,.16);
  background: var(--mg-canvas);
  color: #172333;
  overflow: hidden;
  box-shadow: var(--mg-shadow);
}}

.moon-glass-statusbar {{
  display: grid;
  grid-template-columns: 260px 1fr auto;
  align-items: center;
  gap: 12px;
  padding: 0 14px;
  color: var(--mg-text-muted);
  font-size: 12px;
  background: rgba(9,17,28,.82);
}}

@media (max-width: 980px) {{
  .moon-glass-header {{
    grid-template-columns: 1fr auto;
  }}

  .moon-glass-workspace {{
    grid-template-columns: 48px 1fr;
  }}

  .moon-glass-structure,
  .moon-glass-inspector {{
    display: none;
  }}
}}
""".strip() + "\n"

THEME_JSON_DATA = {
    "slug": THEME_SLUG,
    "name": THEME_NAME,
    "description": "A refined Moon Glass theme for the Agent Meauxbility dashboard and Shopify-quality CMS editor.",
    "css_r2_key": THEME_R2_KEY,
    "css_url": THEME_PUBLIC_URL,
    "tokens": MOON_GLASS_TOKENS,
    "surfaces": {
        "agent": {
            "mode": "vars",
            "notes": "Agent shell should consume variables only unless intentionally testing full visual repaint.",
        },
        "cms": {
            "mode": "full",
            "notes": "CMS editor uses the full Moon Glass CSS theme.",
        },
    },
    "routes": ["/cms", "/cms?view=editor", "/cms?view=pages", "/cms?view=themes", "/cms?view=assets", "/cms?view=sections", "/cms?view=settings"],
}

MOON_GLASS_EDITOR_HTML = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Agent Meauxbility CMS — Moon Glass</title>
  <link rel="stylesheet" href="/api/cms/theme.css?slug=moon-glass&mode=full" data-cms-theme-runtime="true">
  <style>
    * {{
      box-sizing: border-box;
    }}

    html,
    body {{
      margin: 0;
      width: 100%;
      height: 100%;
      overflow: hidden;
      font-family: var(--mg-font-body, Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif);
      background: #172333;
      color: #FAFBFD;
    }}

    button,
    input,
    select,
    textarea {{
      font: inherit;
    }}

    button {{
      cursor: pointer;
    }}

    .mg-logo {{
      width: 24px;
      height: 24px;
      border-radius: 8px;
      object-fit: cover;
    }}

    .brand {{
      display: inline-flex;
      align-items: center;
      gap: 10px;
      min-width: 0;
      color: inherit;
      text-decoration: none;
      font-weight: 800;
      letter-spacing: -0.02em;
    }}

    .brand small {{
      display: block;
      margin-top: 2px;
      color: var(--mg-text-muted);
      font-size: 11px;
      font-weight: 650;
      letter-spacing: 0;
    }}

    .top-tabs,
    .toolbar,
    .section-actions,
    .segmented,
    .icon-row {{
      display: inline-flex;
      align-items: center;
      gap: 8px;
    }}

    .top-tabs a,
    .toolbar a {{
      color: var(--mg-text-secondary);
      text-decoration: none;
      font-size: 13px;
      font-weight: 720;
      padding: 8px 10px;
      border-radius: 999px;
    }}

    .top-tabs a[data-active="true"],
    .top-tabs a:hover,
    .toolbar a:hover {{
      color: var(--mg-text);
      background: rgba(255,255,255,.07);
    }}

    .toolbar button,
    .toolbar select,
    .icon-button,
    .mg-button {{
      height: 34px;
      border-radius: 10px;
      border: 1px solid var(--mg-border);
      color: var(--mg-text);
      background: rgba(255,255,255,.055);
      padding: 0 12px;
    }}

    .mg-button.primary {{
      border-color: rgba(143,215,255,.35);
      background: linear-gradient(135deg, var(--mg-accent), var(--mg-accent-2));
      color: #07111B;
      font-weight: 850;
    }}

    .icon-button {{
      width: 34px;
      display: grid;
      place-items: center;
      padding: 0;
    }}

    .rail-button {{
      width: 34px;
      height: 34px;
      display: grid;
      place-items: center;
      border: 1px solid transparent;
      border-radius: 11px;
      background: transparent;
      color: var(--mg-text-muted);
    }}

    .rail-button[data-active="true"],
    .rail-button:hover {{
      color: var(--mg-text);
      background: rgba(143,215,255,.10);
      border-color: rgba(143,215,255,.18);
    }}

    .panel-header {{
      height: 42px;
      display: flex;
      align-items: center;
      justify-content: space-between;
      padding: 0 14px;
      border-bottom: 1px solid var(--mg-border);
      color: var(--mg-text);
      font-size: 12px;
      font-weight: 850;
      letter-spacing: .08em;
      text-transform: uppercase;
    }}

    .tree {{
      padding: 10px;
      display: grid;
      gap: 5px;
      color: var(--mg-text-secondary);
      font-size: 13px;
    }}

    .tree-item {{
      min-height: 34px;
      display: flex;
      align-items: center;
      gap: 8px;
      padding: 0 10px;
      border-radius: 10px;
    }}

    .tree-item[data-active="true"] {{
      color: var(--mg-text);
      background: linear-gradient(90deg, rgba(79,140,255,.22), rgba(143,215,255,.08));
      border: 1px solid rgba(143,215,255,.18);
    }}

    .tree-sub {{
      padding-left: 18px;
      display: grid;
      gap: 4px;
    }}

    .preview-chrome {{
      width: min(100%, 980px);
      height: min(100%, 760px);
      display: grid;
      grid-template-rows: 50px 1fr;
      border-radius: 16px;
      overflow: hidden;
      border: 1px solid rgba(255,255,255,.18);
      box-shadow: var(--mg-shadow);
      background: white;
      color: #172333;
    }}

    .store-header {{
      display: grid;
      grid-template-columns: 1fr auto 1fr;
      align-items: center;
      padding: 0 28px;
      border-bottom: 1px solid rgba(15,23,42,.10);
      font-size: 14px;
    }}

    .store-nav {{
      display: inline-flex;
      justify-content: center;
      gap: 24px;
    }}

    .store-nav a {{
      color: #172333;
      text-decoration: none;
      font-size: 13px;
    }}

    .store-icons {{
      justify-self: end;
      display: inline-flex;
      gap: 16px;
    }}

    .hero {{
      position: relative;
      min-height: 430px;
      display: grid;
      align-items: center;
      padding: 48px;
      overflow: hidden;
      background:
        radial-gradient(circle at 68% 28%, rgba(255,255,255,.90), transparent 8%),
        linear-gradient(135deg, #F0FBFF, #BFD7EB 48%, #7A8B9E);
    }}

    .hero::before {{
      content: "";
      position: absolute;
      inset: 0;
      opacity: .56;
      background:
        radial-gradient(circle at 24% 68%, rgba(23,35,51,.12), transparent 18%),
        radial-gradient(circle at 84% 80%, rgba(23,35,51,.18), transparent 20%),
        linear-gradient(150deg, transparent 0 48%, rgba(255,255,255,.38) 49% 52%, transparent 53%);
    }}

    .hero-content {{
      position: relative;
      z-index: 1;
      max-width: 390px;
    }}

    .hero h1 {{
      margin: 0 0 20px;
      color: #172333;
      font-size: clamp(34px, 5vw, 58px);
      line-height: 1.02;
      letter-spacing: -0.05em;
    }}

    .hero button {{
      height: 38px;
      padding: 0 22px;
      border-radius: 8px;
      border: 1px solid rgba(23,35,51,.32);
      background: rgba(255,255,255,.42);
      color: #172333;
    }}

    .products {{
      padding: 28px 42px;
      background: white;
    }}

    .products h2 {{
      margin: 0 0 18px;
      font-size: 20px;
      color: #172333;
    }}

    .product-grid {{
      display: grid;
      grid-template-columns: repeat(3, 1fr);
      gap: 18px;
    }}

    .product-card {{
      height: 120px;
      border-radius: 12px;
      background: linear-gradient(135deg, #F8FAFC, #E9EEF4);
      border: 1px solid rgba(15,23,42,.08);
    }}

    .inspector-tabs {{
      height: 42px;
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      border-bottom: 1px solid var(--mg-border);
    }}

    .inspector-tabs button {{
      border: 0;
      background: transparent;
      color: var(--mg-text-muted);
      font-size: 12px;
      font-weight: 700;
    }}

    .inspector-tabs button[data-active="true"] {{
      color: var(--mg-text);
      border-bottom: 2px solid var(--mg-accent-2);
    }}

    .field-list {{
      padding: 14px;
      display: grid;
      gap: 14px;
    }}

    .field {{
      display: grid;
      gap: 7px;
    }}

    .field label {{
      color: var(--mg-text-secondary);
      font-size: 12px;
      font-weight: 750;
    }}

    .field input,
    .field textarea,
    .field select {{
      width: 100%;
      border: 1px solid var(--mg-border);
      border-radius: 10px;
      background: rgba(255,255,255,.055);
      color: var(--mg-text);
      padding: 10px;
      outline: none;
    }}

    .field textarea {{
      min-height: 74px;
      resize: vertical;
    }}

    .status-dot {{
      width: 8px;
      height: 8px;
      border-radius: 999px;
      background: var(--mg-success);
      box-shadow: 0 0 0 4px rgba(52,211,153,.14);
    }}

    .muted {{
      color: var(--mg-text-muted);
    }}
  </style>
</head>
<body>
  <div class="moon-glass-cms moon-glass-editor-shell" data-theme="moon-glass" data-surface="cms">
    <header class="moon-glass-header">
      <a class="brand" href="/">
        <img class="mg-logo" src="{LOGO_URL}" alt="Meauxbility">
        <span>Agent Meauxbility<small>Moon Glass CMS editor</small></span>
      </a>

      <nav class="top-tabs" aria-label="Primary">
        <a href="/">Agents</a>
        <a href="/automations">Automations</a>
        <a href="/dashboard">Dashboard</a>
        <a href="/cms" data-active="true">CMS</a>
      </nav>

      <div class="toolbar">
        <select aria-label="Theme">
          <option>Moon Glass</option>
          <option>IAM Tide Dark</option>
        </select>
        <select aria-label="Page">
          <option>Home page</option>
          <option>About</option>
          <option>Donate</option>
        </select>
        <button class="icon-button" title="Preview">⌕</button>
        <button class="mg-button">Save Draft</button>
        <button class="mg-button primary">Publish</button>
      </div>
    </header>

    <main class="moon-glass-workspace">
      <aside class="moon-glass-rail">
        <div style="display:grid;gap:8px;padding:10px;">
          <button class="rail-button" data-active="true" title="Structure">▦</button>
          <button class="rail-button" title="Settings">⚙</button>
          <button class="rail-button" title="Assets">▧</button>
          <button class="rail-button" title="Theme">◐</button>
          <button class="rail-button" title="Database">▣</button>
          <button class="rail-button" title="Agent">✦</button>
        </div>
      </aside>

      <aside class="moon-glass-structure">
        <div class="panel-header">Structure</div>
        <div class="tree">
          <div class="tree-item">⌄ Header</div>
          <div class="tree-sub">
            <div class="tree-item">Announcement bar</div>
            <div class="tree-item">Navigation</div>
          </div>
          <div class="tree-item" data-active="true">▣ Image banner</div>
          <div class="tree-sub">
            <div class="tree-item">T Heading</div>
            <div class="tree-item">□ Buttons</div>
          </div>
          <div class="tree-item">▦ Featured collection</div>
          <div class="tree-item">⌄ Footer</div>
        </div>
      </aside>

      <section class="moon-glass-preview">
        <div class="preview-chrome">
          <div class="store-header">
            <strong>Nonos Luggage</strong>
            <nav class="store-nav">
              <a href="#">Home</a>
              <a href="#">Catalog</a>
              <a href="#">Contact</a>
            </nav>
            <div class="store-icons">⌕ ♙ ◱</div>
          </div>
          <div style="overflow:auto;">
            <section class="hero">
              <div class="hero-content">
                <h1>Browse our latest products</h1>
                <button>Shop all</button>
              </div>
            </section>
            <section class="products">
              <h2>Featured products</h2>
              <div class="product-grid">
                <div class="product-card"></div>
                <div class="product-card"></div>
                <div class="product-card"></div>
              </div>
            </section>
          </div>
        </div>
      </section>

      <aside class="moon-glass-inspector">
        <div class="inspector-tabs">
          <button data-active="true">Inspector</button>
          <button>Styles</button>
          <button>Console</button>
          <button>Network</button>
        </div>

        <div class="field-list">
          <div class="field">
            <label>Element</label>
            <input value="Image banner">
          </div>

          <div class="field">
            <label>Heading</label>
            <textarea>Browse our latest products</textarea>
          </div>

          <div class="field">
            <label>Height</label>
            <select>
              <option>Large</option>
              <option>Medium</option>
              <option>Small</option>
            </select>
          </div>

          <div class="field">
            <label>Color scheme</label>
            <select>
              <option>Moon Glass</option>
              <option>Light</option>
              <option>Dark</option>
            </select>
          </div>

          <div class="moon-glass-card" style="padding:14px;">
            <div style="display:flex;align-items:center;gap:9px;font-weight:800;">
              <span class="status-dot"></span>
              Theme connected
            </div>
            <p class="muted" style="margin:10px 0 0;font-size:12px;line-height:1.45;">
              This editor is loading Moon Glass through <code>/api/cms/theme.css</code> and is ready for cms_themes validation.
            </p>
          </div>
        </div>
      </aside>
    </main>

    <footer class="moon-glass-statusbar">
      <div>main</div>
      <div><span class="status-dot" style="display:inline-block;margin-right:8px;"></span>No changes</div>
      <div>Auto · HTML · Moon Glass</div>
    </footer>
  </div>
</body>
</html>
"""

THEME_ROUTE_BLOCK = f"""
{THEME_ROUTE_START}
  if (url.pathname === '/api/cms/theme.css') {{
    return handleAgentMeauxbilityThemeCss(request, env);
  }}
{THEME_ROUTE_END}
""".rstrip()

CMS_ROUTE_BLOCK = f"""
{CMS_ROUTE_START}
  if (url.pathname === '/cms' || url.pathname === '/cms/') {{
    return new Response(MOON_GLASS_CMS_EDITOR_HTML, {{
      status: 200,
      headers: {{
        'content-type': 'text/html;charset=UTF-8',
        'cache-control': 'no-store'
      }}
    }});
  }}
{CMS_ROUTE_END}
""".rstrip()

THEME_HELPER = r"""
// AGENT_MEAUXBILITY_THEME_CSS_HELPER_START
function agentMeauxbilitySafeJson(raw, fallback = {}) {
  if (!raw || typeof raw !== 'string') return fallback;
  try {
    const parsed = JSON.parse(raw);
    return parsed && typeof parsed === 'object' ? parsed : fallback;
  } catch (_) {
    return fallback;
  }
}

function agentMeauxbilityCssVarName(key) {
  const clean = String(key || '')
    .replace(/[A-Z]/g, m => '-' + m.toLowerCase())
    .replace(/[^a-z0-9_-]/gi, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
  return clean.startsWith('--') ? clean : `--${clean}`;
}

function agentMeauxbilityCssVarsFromObject(obj, prefix = '') {
  const lines = [];
  for (const [key, value] of Object.entries(obj || {})) {
    if (value === null || value === undefined) continue;
    if (typeof value === 'object') continue;
    const name = agentMeauxbilityCssVarName(prefix ? `${prefix}-${key}` : key);
    const val = String(value).replace(/[;{}]/g, '');
    lines.push(`  ${name}: ${val};`);
  }
  return lines.join('\n');
}

function agentMeauxbilityThemeImport(cssUrl, mode = 'vars') {
  if (mode !== 'full') return '';
  if (!cssUrl || typeof cssUrl !== 'string') return '';
  const safe = cssUrl.trim();
  if (!safe.startsWith('https://assets.inneranimalmedia.com/')) return '';
  return `@import url("${safe}");\n\n`;
}

async function handleAgentMeauxbilityThemeCss(request, env) {
  const url = new URL(request.url);
  const slug = url.searchParams.get('slug') || 'moon-glass';
  const mode = url.searchParams.get('mode') || 'vars';

  let theme = null;
  let warning = '';

  try {
    if (env.DB) {
      theme = await env.DB.prepare(`
        SELECT
          name,
          slug,
          css_url,
          css_vars_json,
          tokens_json,
          brand_json,
          layout_json,
          typography_json,
          components_json,
          motion_json,
          updated_at
        FROM cms_themes
        WHERE slug = ?
          AND status = 'active'
        LIMIT 1
      `).bind(slug).first();
    } else {
      warning = 'missing DB binding';
    }
  } catch (err) {
    warning = err && err.message ? err.message : String(err);
  }

  const cssVars = agentMeauxbilitySafeJson(theme && theme.css_vars_json, {});
  const tokens = agentMeauxbilitySafeJson(theme && theme.tokens_json, {});
  const brand = agentMeauxbilitySafeJson(theme && theme.brand_json, {});
  const layout = agentMeauxbilitySafeJson(theme && theme.layout_json, {});
  const typography = agentMeauxbilitySafeJson(theme && theme.typography_json, {});
  const components = agentMeauxbilitySafeJson(theme && theme.components_json, {});

  const css = `${agentMeauxbilityThemeImport(theme && theme.css_url, mode)}
/*
  Agent Meauxbility runtime CMS theme
  slug: ${theme && theme.slug ? theme.slug : slug}
  name: ${theme && theme.name ? theme.name : 'fallback'}
  updated_at: ${theme && theme.updated_at ? theme.updated_at : 'n/a'}
  warning: ${warning || 'none'}
*/
:root {
${agentMeauxbilityCssVarsFromObject(cssVars)}
${agentMeauxbilityCssVarsFromObject(tokens, 'theme')}
${agentMeauxbilityCssVarsFromObject(brand, 'brand')}
${agentMeauxbilityCssVarsFromObject(layout, 'layout')}
${agentMeauxbilityCssVarsFromObject(typography, 'typography')}
${agentMeauxbilityCssVarsFromObject(components, 'component')}
}
`;

  return new Response(css, {
    status: 200,
    headers: {
      'content-type': 'text/css;charset=UTF-8',
      'cache-control': 'no-store'
    }
  });
}
// AGENT_MEAUXBILITY_THEME_CSS_HELPER_END
""".strip()


def now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.%fZ")


def stamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")


def run(cmd: list[str], *, check: bool = True, input_text: str | None = None) -> subprocess.CompletedProcess[str]:
    print("+", " ".join(cmd))
    proc = subprocess.run(cmd, cwd=ROOT, text=True, input=input_text, capture_output=True)
    if proc.stdout:
        print(proc.stdout.rstrip())
    if proc.stderr:
        print(proc.stderr.rstrip(), file=sys.stderr)
    if check and proc.returncode != 0:
        raise SystemExit(f"command failed ({proc.returncode}): {' '.join(cmd)}")
    return proc


def backup(path: Path) -> None:
    if path.exists():
        dst = path.with_suffix(path.suffix + ".backup.moon-glass." + stamp())
        shutil.copy2(path, dst)
        print(f"backup -> {dst}")


def write_files() -> None:
    THEME_DIR.mkdir(parents=True, exist_ok=True)
    CMS_HTML.parent.mkdir(parents=True, exist_ok=True)
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)

    css_hash = hashlib.sha256(MOON_GLASS_CSS.encode("utf-8")).hexdigest()
    theme_json = {
        **THEME_JSON_DATA,
        "compiled_css_hash": css_hash,
        "generated_at": now(),
    }

    THEME_CSS.write_text(MOON_GLASS_CSS)
    THEME_JSON.write_text(json.dumps(theme_json, indent=2) + "\n")
    CMS_HTML.write_text(MOON_GLASS_EDITOR_HTML)

    html = CMS_HTML.read_text()
    GENERATED_JS.write_text(
        "// Generated by scripts/cms/part5_moon_glass_cms_full_install.py\n"
        "// Source: public/cms/moon-glass-editor.html\n\n"
        "export const MOON_GLASS_CMS_EDITOR_HTML = " + json.dumps(html) + ";\n"
    )

    print(f"wrote -> {THEME_CSS}")
    print(f"wrote -> {THEME_JSON}")
    print(f"wrote -> {CMS_HTML}")
    print(f"wrote -> {GENERATED_JS}")


def strip_between(text: str, start: str, end: str) -> str:
    return re.sub(re.escape(start) + r".*?" + re.escape(end), "", text, flags=re.S)


def insert_import(worker: str) -> str:
    if IMPORT_LINE in worker:
        return worker

    if worker.lstrip().startswith("import "):
        return IMPORT_LINE + "\n" + worker

    return IMPORT_LINE + "\n" + worker


def insert_after_url(worker: str, block: str) -> str:
    patterns = [
        r"(const\s+url\s*=\s*new\s+URL\s*\(\s*request\.url\s*\)\s*;)",
        r"(let\s+url\s*=\s*new\s+URL\s*\(\s*request\.url\s*\)\s*;)",
        r"(var\s+url\s*=\s*new\s+URL\s*\(\s*request\.url\s*\)\s*;)",
    ]
    for pattern in patterns:
        m = re.search(pattern, worker)
        if m:
            return worker[:m.end()] + "\n" + block + worker[m.end():]
    raise SystemExit("Could not find new URL(request.url) insertion point in worker.js")


def patch_worker() -> None:
    if not WORKER.exists():
        raise SystemExit("worker.js not found")

    backup(WORKER)
    worker = WORKER.read_text(errors="replace")

    worker = insert_import(worker)

    worker = strip_between(worker, CMS_ROUTE_START, CMS_ROUTE_END)
    worker = strip_between(worker, THEME_ROUTE_START, THEME_ROUTE_END)
    worker = strip_between(worker, THEME_HELPER_START, THEME_HELPER_END)

    # If the older CMS route block exists, remove it so /cms uses Moon Glass.
    worker = strip_between(worker, "// AGENT_MEAUXBILITY_CMS_ROUTE_START", "// AGENT_MEAUXBILITY_CMS_ROUTE_END")

    worker = insert_after_url(worker, THEME_ROUTE_BLOCK + "\n" + CMS_ROUTE_BLOCK)

    worker = worker.rstrip() + "\n\n" + THEME_HELPER + "\n"

    WORKER.write_text(worker)
    print(f"patched -> {WORKER}")


def write_smoke() -> None:
    SMOKE.parent.mkdir(parents=True, exist_ok=True)
    SMOKE.write_text("""#!/usr/bin/env bash
set -euo pipefail

BASE="${AGENT_MEAUXBILITY_APP_URL:-https://agent.meauxbility.workers.dev}"

echo "== /cms =="
/usr/bin/curl -I "$BASE/cms" | /usr/bin/sed -n '1,14p'

echo ""
echo "== /cms markers =="
/usr/bin/curl -sS "$BASE/cms" | /usr/bin/grep -nE "Moon Glass CMS editor|moon-glass-editor-shell|moon-glass-workspace|Theme connected" | /usr/bin/head -20

echo ""
echo "== theme vars =="
/usr/bin/curl -sS "$BASE/api/cms/theme.css?slug=moon-glass&mode=vars" | /usr/bin/head -80

echo ""
echo "== theme full import =="
/usr/bin/curl -sS "$BASE/api/cms/theme.css?slug=moon-glass&mode=full" | /usr/bin/grep -n "@import" || true
""")
    SMOKE.chmod(0o755)
    print(f"wrote -> {SMOKE}")


def wrangler_available() -> bool:
    return shutil.which("npx") is not None


def get_env() -> dict[str, str]:
    return dict(os.environ)


def r2_upload(skip: bool) -> None:
    if skip:
        print("skip R2 upload")
        return

    env = get_env()
    if not env.get("CLOUDFLARE_API_TOKEN"):
        print("skip R2 upload: missing CLOUDFLARE_API_TOKEN")
        return

    bucket = env.get("CLOUDFLARE_R2_BUCKET") or "inneranimalmedia"

    run(["npx", "wrangler", "r2", "object", "put", f"{bucket}/{THEME_R2_KEY}", "--file", str(THEME_CSS), "--remote"])
    run(["npx", "wrangler", "r2", "object", "put", f"{bucket}/{THEME_JSON_R2_KEY}", "--file", str(THEME_JSON), "--remote"])


def extract_d1_results(payload: Any) -> list[dict[str, Any]]:
    if isinstance(payload, list) and payload:
        first = payload[0]
        if isinstance(first, dict):
            if isinstance(first.get("results"), list):
                return first["results"]
            if isinstance(first.get("result"), list):
                return first["result"]
    if isinstance(payload, dict):
        if isinstance(payload.get("results"), list):
            return payload["results"]
        if isinstance(payload.get("result"), list):
            return payload["result"]
    return []


def d1_json(command: str) -> list[dict[str, Any]]:
    db = os.environ.get("IAM_D1_DB") or "inneranimalmedia-business"
    proc = run(["npx", "wrangler", "d1", "execute", db, "--remote", "--json", "--command", command])
    try:
        payload = json.loads(proc.stdout)
    except json.JSONDecodeError as exc:
        raise SystemExit(f"Could not parse wrangler D1 JSON: {exc}\nstdout:\n{proc.stdout}")
    return extract_d1_results(payload)


def sql_quote(value: Any) -> str:
    if value is None:
        return "NULL"
    s = str(value)
    return "'" + s.replace("'", "''") + "'"


def upsert_cms_theme(skip: bool) -> None:
    if skip:
        print("skip D1 upsert")
        return

    env = get_env()
    if not env.get("CLOUDFLARE_API_TOKEN"):
        print("skip D1 upsert: missing CLOUDFLARE_API_TOKEN")
        return

    db = env.get("IAM_D1_DB") or "inneranimalmedia-business"

    cols_info = d1_json("PRAGMA table_info(cms_themes);")
    cols = [str(row.get("name")) for row in cols_info if row.get("name")]
    if not cols:
        raise SystemExit("Could not inspect cms_themes columns.")

    css_hash = hashlib.sha256(THEME_CSS.read_bytes()).hexdigest()

    values: dict[str, Any] = {
        "id": "theme_moon_glass",
        "tenant_id": env.get("IAM_TENANT_ID") or "tenant_sam_primeaux",
        "workspace_id": env.get("IAM_WORKSPACE_ID") or "ws_inneranimalmedia",
        "name": THEME_NAME,
        "slug": THEME_SLUG,
        "description": "A refined Moon Glass theme for the Agent Meauxbility dashboard and Shopify-quality CMS editor.",
        "config": json.dumps(THEME_JSON_DATA, separators=(",", ":")),
        "status": "active",
        "mode": "auto",
        "theme_type": "editor",
        "category": "editor",
        "css_r2_bucket": env.get("CLOUDFLARE_R2_BUCKET") or "inneranimalmedia",
        "r2_bucket": env.get("CLOUDFLARE_R2_BUCKET") or "inneranimalmedia",
        "css_r2_key": THEME_R2_KEY,
        "r2_key": THEME_R2_KEY,
        "css_url": THEME_PUBLIC_URL,
        "preview_image_url": "",
        "compiled_css_hash": css_hash,
        "tokens_json": json.dumps(MOON_GLASS_TOKENS, separators=(",", ":")),
        "css_vars_json": json.dumps({
            "--mg-shell-bg": "#172333",
            "--mg-panel": "#1E2A3A",
            "--mg-border": "#2E3B4E",
            "--mg-text": "#FAFBFD",
            "--mg-text-secondary": "#C7D0DB",
            "--mg-accent": "#4F8CFF",
            "--mg-accent-2": "#8FD7FF",
            "--mg-glow": "#F0FBFF",
        }, separators=(",", ":")),
        "brand_json": json.dumps({
            "logo_url": LOGO_URL,
            "name": "Agent Meauxbility",
            "style": "moon-glass",
        }, separators=(",", ":")),
        "layout_json": json.dumps({
            "editor_grid": "rail structure preview inspector",
            "header_height": "56px",
            "statusbar_height": "28px",
        }, separators=(",", ":")),
        "typography_json": json.dumps({
            "body": "Inter",
            "display": "Inter",
            "mono": "JetBrains Mono",
        }, separators=(",", ":")),
        "components_json": json.dumps({
            "header": "moon-glass-header",
            "editor": "moon-glass-editor-shell",
            "structure": "moon-glass-structure",
            "inspector": "moon-glass-inspector",
            "preview": "moon-glass-preview",
        }, separators=(",", ":")),
        "motion_json": json.dumps({
            "reduced_motion": True,
            "transitions": "subtle",
        }, separators=(",", ":")),
        "metadata_json": json.dumps(THEME_JSON_DATA, separators=(",", ":")),
        "created_at": now(),
        "updated_at": now(),
    }

    usable = {k: v for k, v in values.items() if k in cols}
    if "slug" not in usable:
        raise SystemExit("cms_themes has no slug column; refusing upsert.")

    update_cols = [k for k in usable.keys() if k not in {"id", "slug", "created_at"}]
    update_sql = ",\n  ".join(f"{k} = {sql_quote(usable[k])}" for k in update_cols)

    insert_cols = list(usable.keys())
    insert_vals = [sql_quote(usable[k]) for k in insert_cols]

    sql = f"""
UPDATE cms_themes
SET
  {update_sql}
WHERE slug = {sql_quote(THEME_SLUG)};

INSERT INTO cms_themes ({", ".join(insert_cols)})
SELECT {", ".join(insert_vals)}
WHERE NOT EXISTS (
  SELECT 1 FROM cms_themes WHERE slug = {sql_quote(THEME_SLUG)}
);

SELECT slug, name, status, css_url, css_r2_key, compiled_css_hash, updated_at
FROM cms_themes
WHERE slug = {sql_quote(THEME_SLUG)};
""".strip()

    with tempfile.NamedTemporaryFile("w", suffix=".sql", delete=False) as f:
        f.write(sql)
        tmp_sql = f.name

    try:
        run(["npx", "wrangler", "d1", "execute", db, "--remote", "--file", tmp_sql])
    finally:
        try:
            Path(tmp_sql).unlink()
        except OSError:
            pass


def deploy(skip: bool) -> None:
    if skip:
        print("skip deploy")
        return

    if not os.environ.get("CLOUDFLARE_API_TOKEN"):
        print("skip deploy: missing CLOUDFLARE_API_TOKEN")
        return

    run(["npx", "wrangler", "deploy", "--dry-run", "-c", "wrangler.json"])
    run(["npx", "wrangler", "deploy", "-c", "wrangler.json"])


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--no-upload", action="store_true", help="Do not upload theme artifacts to R2.")
    parser.add_argument("--no-db", action="store_true", help="Do not upsert cms_themes.")
    parser.add_argument("--no-deploy", action="store_true", help="Do not deploy worker.")
    args = parser.parse_args()

    if not wrangler_available():
        print("warning: npx not found; local files will be created but Cloudflare steps may fail/skip.")

    write_files()
    patch_worker()
    write_smoke()
    r2_upload(skip=args.no_upload)
    upsert_cms_theme(skip=args.no_db)
    deploy(skip=args.no_deploy)

    print()
    print("Done.")
    print("Validate:")
    print("  scripts/cms/smoke_moon_glass_cms.sh")
    print("  open https://agent.meauxbility.workers.dev/cms")
    print("  curl -sS 'https://agent.meauxbility.workers.dev/api/cms/theme.css?slug=moon-glass&mode=full' | head -80")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
